#!/bin/bash
#
# readsegy (Shell Script)
# 
# Purpose: User interface to call shell script readsegy programs.
# 
# Site: http://www.dirackslounge.online
# 
# Version 1.0
# 
# Programer: Rodolfo Dirack 23/02/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Program version
VERSION="1.0"

# Debug option (Only for programers)
# Use DEBUG=1 to run program in debug mode
DEBUG=0

[ "$DEBUG" -eq "1" ] && {

	set -xv

}

# Check for the shell scripts dependencies
IMPORT_SCRIPT="01_import_segy.sh"
SELECT_SHOTS_SCRIPT="02_selectshots_savesegy.sh"
SORT_SCRIPT="03_sort.sh"

[ -f "$IMPORT_SCRIPT" -a -f "$SELECT_SHOTS_SCRIPT" -a -f "$SORT_SCRIPT" ] || {
	echo "Some program dependencies not found in this repository!"
	exit 1
}

# Force user to choose an option
[ -z "$1" ] && {
	echo "You should choose an option"
	echo "type $(basename $0) -h to get help"
	exit 1
}

# Help mesage
PROGRAM="$(basename $0) [ -h | -v | -i | -s | -o ]"
DESCRIPTION="Script to manipulate segy files using seismic unix"
PARAMETERS="-h --help Display help and exit
-v --version Display program version and exit
-i --import Import segy data
-s --select Select Shots
-o --sort Trace Sorting"

case "$1" in

	-h | --help)

		clear
		echo -e "\n$PROGRAM\n"
		echo -e "$DESCRIPTION\n"
		echo -e "$PARAMETERS\n"
		exit 0
		;;

	-v | --version)
		
		echo "$(basename "$0") $VERSION"
		exit 0
		;;

	-i | --import) # Import segy data

			./01_import_segy.sh
		;;
		
	-s | --select) # Select Shots

			./02_selectshots_savesegy.sh
		;;

	-o | --sort) # Trace Sorting

			./03_sort.sh
		;;

	*)

		echo -e "Option $1 is unknown!\nType $0 -h to get help."
		exit 1
		;;
esac

exit 0
