#!/bin/bash
#
# readsegy (Shell Script)
# 
# Purpose: User interface to call shell script readsegy programs.
# 
# Site: http://www.dirackslounge.online
# 
# Version 1.0
# 
# Programer: Rodolfo Dirack 23/02/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Program version
VERSION="1.0"

# Debug option (Only for programers)
# Use DEBUG=1 to run program in debug mode
DEBUG=0

[ "$DEBUG" -eq "1" ] && {

	set -xv

}

# Check for the shell scripts dependencies
IMPORT_SCRIPT="01_import_segy.sh"
SELECT_SHOTS_SCRIPT="02_selectshots_savesegy.sh"
SORT_SCRIPT="03_sort.sh"
[ -f "$IMPORT_SCRIPT" -a -f "$SELECT_SHOTS_SCRIPT" -a -f "$SORT_SCRIPT" ] || {
	echo "Some program dependencies not found in this repository!"
	exit 1
}



